# Generated by Django 4.2.3 on 2024-02-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization_service', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='activated_referral_code',
            field=models.CharField(default=None, max_length=8, null=True),
        ),
    ]
